import { ArrowForward, Inventory2Outlined, LocalShippingOutlined, NorthEast, WarningAmberRounded } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardContent, CircularProgress, Divider, LinearProgress, Stack, Typography } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { api } from '../api/client';
import { PageHeader } from '../components/PageHeader';
interface Summary{orders:Array<{status:string;count:number}>;products:Array<{status:string;count:number}>;users:{total:number};revenue:{completedRevenue:string|null};reviews:{total:number;averageRating:string|null}}
interface AuditItem{id:string;action:string;resourceType:string;actorEmail:string|null;createdAt:string}

export function DashboardPage() {
  const summary=useQuery({queryKey:['analytics-summary'],queryFn:({signal})=>api<Summary>('/admin/analytics/summary',{signal})});
  const audit=useQuery({queryKey:['recent-audit'],queryFn:({signal})=>api<{items:AuditItem[]}>('/admin/audit?limit=6',{signal})});
  if(summary.isLoading)return <Box sx={{height:420,display:'grid',placeItems:'center'}}><CircularProgress aria-label="Loading dashboard"/></Box>;
  if(summary.isError||!summary.data)return <Alert severity="error" action={<Button onClick={()=>void summary.refetch()}>Retry</Button>}>Dashboard data could not be loaded.</Alert>;
  const totalOrders=summary.data.orders.reduce((total,item)=>total+item.count,0);const pending=summary.data.orders.filter((item)=>item.status!=='cancelled').reduce((total,item)=>total+item.count,0);const active=summary.data.products.find((item)=>item.status==='active')?.count??0;const drafts=summary.data.products.find((item)=>item.status==='draft')?.count??0;
  const metrics=[{label:'Completed revenue',value:new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(summary.data.revenue.completedRevenue??0)),note:`${totalOrders} total orders`,icon:<NorthEast/>,tone:'#E5F0E8'},{label:'Orders to fulfil',value:String(pending),note:'Open order workload',icon:<LocalShippingOutlined/>,tone:'#E7EEF2'},{label:'Customer accounts',value:String(summary.data.users.total),note:`${summary.data.reviews.total} reviews`,icon:<WarningAmberRounded/>,tone:'#F7E8D6'},{label:'Active products',value:String(active),note:`${drafts} drafts`,icon:<Inventory2Outlined/>,tone:'#F1EDE7'}];
  return <>
    <PageHeader eyebrow="Overview" title="Good afternoon, Ananya." description="Here is what needs attention across your store today." action={<Button href="/products" variant="contained" endIcon={<ArrowForward />}>View products</Button>} />
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', xl: 'repeat(4, 1fr)' }, gap: 2, mb: 3 }}>
      {metrics.map((metric) => <Card key={metric.label}><CardContent sx={{ p: 2.5 }}><Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}><Typography color="text.secondary" fontSize={13} fontWeight={700}>{metric.label}</Typography><Box sx={{ width: 34, height: 34, display: 'grid', placeItems: 'center', borderRadius: 2, bgcolor: metric.tone, color: 'primary.main' }}>{metric.icon}</Box></Box><Typography variant="h2" sx={{ fontFamily: 'DM Sans', fontSize: '1.9rem', fontWeight: 700 }}>{metric.value}</Typography><Typography variant="caption" color="text.secondary">{metric.note}</Typography></CardContent></Card>)}
    </Box>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: 'minmax(0,1.4fr) minmax(320px,.8fr)' }, gap: 3 }}>
      <Card><CardContent sx={{ p: 0 }}><Box sx={{ px: 3, py: 2.5 }}><Typography component="h2" variant="h3">Orders by status</Typography><Typography variant="body2" color="text.secondary">Live operational distribution</Typography></Box><Divider /><Box sx={{ p: 3 }}><Box sx={{ height: 220, display: 'flex', alignItems: 'flex-end', gap: 2, borderBottom: '1px solid', borderColor: 'divider' }}>{summary.data.orders.map((item) => <Box key={item.status} sx={{ flex: 1, textAlign: 'center' }}><Box sx={{ height: `${Math.max(12,totalOrders?item.count/totalOrders*100:0)}%`, minHeight: 20, bgcolor: item.status==='cancelled'?'warning.main':'primary.main', borderRadius: '7px 7px 2px 2px' }} /><Typography variant="caption" color="text.secondary">{item.status}</Typography></Box>)}</Box><Stack direction="row" justifyContent="space-between" sx={{ mt: 2 }}><Typography variant="body2" color="text.secondary">{totalOrders} orders</Typography><Typography variant="body2" fontWeight={700} color="success.main">Live</Typography></Stack></Box></CardContent></Card>
      <Card><CardContent sx={{ p: 0 }}><Box sx={{ px: 3, py: 2.5, display: 'flex', justifyContent: 'space-between' }}><Box><Typography component="h2" variant="h3">Recent activity</Typography><Typography variant="body2" color="text.secondary">Asia/Kolkata</Typography></Box><Button disabled size="small">View all</Button></Box><Divider />
        <Box component="ol" sx={{ m: 0, p: 3, listStyle: 'none' }}>{(audit.data?.items??[]).map((item, index,items) => <Box component="li" key={item.id} sx={{ display: 'grid', gridTemplateColumns: '16px 1fr', gap: 1.5, position: 'relative', pb: index === items.length - 1 ? 0 : 2.5, '&::after': index === items.length - 1 ? {} : { content: '""', position: 'absolute', left: 7, top: 16, bottom: 0, width: 2, bgcolor: 'secondary.light' } }}><Box sx={{ width: 10, height: 10, mt: .6, borderRadius: '50%', bgcolor: 'secondary.main', zIndex: 1 }} /><Box><Typography variant="body2"><strong>{item.actorEmail??'System'}</strong> {item.action} <strong>{item.resourceType}</strong></Typography><Typography variant="caption" color="text.secondary">{new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.createdAt))}</Typography></Box></Box>)}</Box>
      </CardContent></Card>
    </Box>
    <Card sx={{ mt: 3, bgcolor: '#EFF1EB' }}><CardContent sx={{ p: 3, display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 4, alignItems: 'center' }}><Box><Typography variant="overline" color="secondary.main" fontWeight={800}>Stock health</Typography><Typography component="h2" variant="h2">93% of active variants are ready to sell.</Typography></Box><Box><Stack direction="row" justifyContent="space-between" mb={1}><Typography variant="body2" fontWeight={700}>In-stock coverage</Typography><Typography variant="body2">93%</Typography></Stack><LinearProgress variant="determinate" value={93} sx={{ height: 9, borderRadius: 5, bgcolor: '#DDE1D8', '& .MuiLinearProgress-bar': { borderRadius: 5 } }} /></Box></CardContent></Card>
  </>;
}
