import { Refresh } from '@mui/icons-material';import { Alert,Box,Button,Card,CircularProgress,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Typography } from '@mui/material';import { useQuery } from '@tanstack/react-query';import { useEffect } from 'react';import { useLocation } from 'react-router-dom';import { api } from '../api/client';import { PageHeader } from '../components/PageHeader';
interface Config{title:string;eyebrow:string;detail:string;endpoint:string;columns:Array<[string,string]>}const configs:Record<string,Config>={
'/categories':{title:'Categories',eyebrow:'Catalog',detail:'Men, Women, Kids and extensible clothing taxonomy.',endpoint:'/admin/categories',columns:[['name','Name'],['audience','Audience'],['slug','Slug'],['sortOrder','Order']]},
'/collections':{title:'Collections',eyebrow:'Merchandising',detail:'Curated and scheduled product edits.',endpoint:'/admin/collections',columns:[['name','Name'],['collectionType','Type'],['status','Status'],['priority','Priority']]},
'/campaigns':{title:'Campaigns',eyebrow:'Merchandising',detail:'Seasonal and festival publication windows.',endpoint:'/admin/campaigns',columns:[['name','Name'],['slug','Slug'],['status','Status'],['priority','Priority']]},
'/promotions':{title:'Promotions',eyebrow:'Merchandising',detail:'Offers, codes, scopes and schedules.',endpoint:'/admin/promotions',columns:[['name','Name'],['code','Code'],['discountType','Type'],['discountValue','Value'],['status','Status']]},
'/banners':{title:'Banners',eyebrow:'Content',detail:'Responsive internal campaign creative by placement.',endpoint:'/admin/banners',columns:[['name','Name'],['placement','Placement'],['status','Status'],['priority','Priority']]},
'/homepage':{title:'Homepage layout',eyebrow:'Content',detail:'Published homepage compositions and section order.',endpoint:'/admin/homepage-layouts',columns:[['name','Name'],['slug','Slug'],['status','Status'],['priority','Priority']]},
'/recommendations':{title:'Recommendation rules',eyebrow:'Merchandising',detail:'Explainable deterministic product-placement strategies.',endpoint:'/admin/recommendation-rules',columns:[['name','Name'],['placement','Placement'],['strategy','Strategy'],['status','Status'],['priority','Priority']]},
'/orders':{title:'Orders',eyebrow:'Operations',detail:'Order lifecycle, fulfilment and returns.',endpoint:'/admin/orders',columns:[['id','Order'],['status','Status'],['total','Total'],['createdAt','Created']]},
'/customers':{title:'Customers',eyebrow:'Relationships',detail:'Customer accounts and order activity.',endpoint:'/admin/customers',columns:[['email','Email'],['status','Status'],['orderCount','Orders'],['createdAt','Joined']]},
'/analytics':{title:'Analytics',eyebrow:'Performance',detail:'Live store performance from Mercury.',endpoint:'/admin/analytics/summary',columns:[]},
'/team':{title:'Team & roles',eyebrow:'Access',detail:'Backoffice identities and precise permissions.',endpoint:'/admin/users',columns:[['email','Email'],['status','Status'],['roles','Roles'],['createdAt','Created']]},
'/activity':{title:'Activity log',eyebrow:'Accountability',detail:'Chronological changes across the store.',endpoint:'/admin/audit',columns:[['action','Action'],['resourceType','Resource'],['actorEmail','Actor'],['createdAt','At']]},
'/settings':{title:'Store settings',eyebrow:'Configuration',detail:'Brand identity, India locale, INR and tax defaults.',endpoint:'/admin/settings/store',columns:[]}};
function valueAt(row:Record<string,unknown>,key:string){const value=row[key];if(Array.isArray(value))return value.join(', ');if(value===null||value===undefined)return '—';if(typeof value==='object')return JSON.stringify(value);if(key.toLowerCase().includes('at')){const date=new Date(String(value));if(!Number.isNaN(date.getTime()))return new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(date);}return String(value);}
export function ModulePage(){const location=useLocation();const config=configs[location.pathname];useEffect(()=>{document.title=`${config?.title??'Page not found'} — Mercury Backoffice`;},[config]);const query=useQuery({queryKey:['admin-module',location.pathname],enabled:Boolean(config),queryFn:({signal})=>api<unknown>(config!.endpoint,{signal})});if(!config)return <PageHeader title="Page not found" eyebrow="404" description="This page does not exist."/>;const raw=query.data;const rows=Array.isArray(raw)?raw:(raw&&typeof raw==='object'&&Array.isArray((raw as {items?:unknown}).items)?(raw as {items:unknown[]}).items:[]);return <><PageHeader title={config.title} eyebrow={config.eyebrow} description={config.detail} action={<Button startIcon={<Refresh/>} onClick={()=>void query.refetch()} disabled={query.isFetching}>Refresh</Button>}/><Card sx={{minHeight:360}}>{query.isLoading?<Box sx={{height:360,display:'grid',placeItems:'center'}}><CircularProgress aria-label={`Loading ${config.title}`}/></Box>:query.isError?<Alert severity="error" action={<Button onClick={()=>void query.refetch()}>Retry</Button>}>{config.title} could not be loaded.</Alert>:config.columns.length?<TableContainer><Table aria-label={config.title}><TableHead><TableRow>{config.columns.map(([,label])=><TableCell key={label}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map((item,index)=>{const row=item as Record<string,unknown>;return <TableRow key={String(row.id??index)} hover>{config.columns.map(([key,label])=><TableCell key={label}>{valueAt(row,key)}</TableCell>)}</TableRow>})}{rows.length===0&&<TableRow><TableCell colSpan={config.columns.length} align="center" sx={{py:8}}><Typography variant="h3">No records yet</Typography><Typography color="text.secondary">Create the first record when you are ready.</Typography></TableCell></TableRow>}</TableBody></Table></TableContainer>:<Box sx={{p:3,display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,minmax(0,1fr))'},gap:2}}>{raw&&typeof raw==='object'?Object.entries(raw as Record<string,unknown>).map(([key,value])=><Card variant="outlined" key={key} sx={{p:2}}><Typography variant="caption" color="text.secondary">{key.replaceAll('_',' ')}</Typography><Typography variant="h3" sx={{mt:.5,wordBreak:'break-word'}}>{typeof value==='object'?JSON.stringify(value):String(value)}</Typography></Card>):<Typography color="text.secondary">No configuration returned.</Typography>}</Box>}</Card></>}
